//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{

	public class Node : MonoBehavior
		{

		Node[] adjacents = new Node[4];
		Vector3 nodePosition = gameObject.transform.position;
		float distance;

				
				public Node (Transform destination)
				{
				
				distance = Vector3.Distance (nodePosition, destination.position);
				
				

				}
		}
}

